dist: xenial
language: java
os:
  - linux
jdk:
  - openjdk11

before_install: mvn -B -V initialize -P setVersion

stages:
  - name: Tests
  - name: Prerelease
    if: type = push AND tag IS present AND tag =~ ^v\d+\.\d+(\.\d+)?-.*$
  - name: Release
    if: type = push AND tag IS present AND tag =~ ^v\d+\.\d+(\.\d+)?$

jobs:
  include:
    # ------------------------------
    # Test stage
    # ------------------------------
    - stage: Tests
      name: "Frontend Tests"
      install: skip
      script:
        - mvn -B -V -T 1C install -N
        - mvn -B -V install -pl frontend-resources
        - mvn -B -V -T 1C install -pl backend -DskipTests
        - mvn -B -V -T 1C package -pl executable

    #build backend and run all non-integration tests
    - stage: Tests
      name: "Unit Tests"
      install:
        - cd backend
        - mvn -B -V -T 1C install -DskipTests
      script: mvn -B test -DexcludedGroups="INTEGRATION_PROGRAMMATIC, INTEGRATION_JSON"

    #build and test only INTEGRATION_PROGRAMMATIC
    - stage: Tests
      name: "Programmatic Integration Tests"
      install:
        - cd backend
        - mvn -B -V -T 1C install -DskipTests
      script: mvn -B test -Dgroups="INTEGRATION_PROGRAMMATIC"

    #build and test only INTEGRATION_JSONs
    - stage: Tests
      name: "Integration Tests"
      install:
        - cd backend
        - mvn -B -V -T 1C install -DskipTests
      script: mvn -B test -Dgroups="INTEGRATION_JSON"

    # ------------------------------
    # Release stages
    # ------------------------------

    - stage: Prerelease
      install: mvn -B -V package -DskipTests
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        tag_name: $TRAVIS_TAG
        target_commitish: $TRAVIS_COMMIT
        file_glob: true
        file:
          - backend/target/backend-*.jar
          - executable/target/executable-*.jar
        skip_cleanup: true
        draft: false
        prerelease: true
        on:
          all_branches: true

    - stage: Release
      install: mvn -B -V package -DskipTests
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        tag_name: $TRAVIS_TAG
        target_commitish: $TRAVIS_COMMIT
        file_glob: true
        file:
          - backend/target/backend-*.jar
          - executable/target/executable-*.jar
        skip_cleanup: true
        draft: false
        prerelease: false
        on:
          all_branches: true

#remove the installed maven jars before caching
before_cache:
  - rm -f -r $HOME/.m2/repository/com/bakdata/conquery/
cache:
  yarn: true
  directories:
    - "$HOME/.cache"
    - "$HOME/.m2"
